### ISSUE TITLE
urllib.parse not importing

### ISSUE THREAD

**Issue by Yoposoc** [iyra/moar-chives#1] opened 2017-08-29 04:17 UTC
Hello, I'm a noob at this, but I have Python 3.x and I'm trying to use the script. Currently it's telling me that urllib.parse isn't importing, any clue?

**Comment by iyra** [comment] 2017-08-29 11:31
Hi,
So, firstly I made a mistake in my README, you should run it as `python3 archive.py url1 url2 ...`.

I am using Python 3.4.5 on Linux and urllib.parse exists. 

Can you tell me what happens when you launch the Python 3 interpreter and do `import urllib.parse`? And are you sure that you're running the script with Python 3?

Py 3 isn't the default on many distributions, so you may have to use `python3` rather than just `python`.

**Comment by iyra** [comment] 2018-01-28 01:10
Closing this because I haven't been able to reproduce it.

**Closed by iyra** 2018-01-28 01:10 UTC
